#!/usr/bin/env node
/**
 * Sync the static site with the repository.
 *
 * The site is not a re-implementation of the product. It runs the same wall
 * logic and the same bootstrap set, copied here at build time so the folder can
 * be deployed on its own. Anything this script writes is generated — edit the
 * source, not the copy.
 */
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SITE = join(ROOT, 'site');

const BANNER = '/* GENERATED by scripts/build-site.mjs — edit src/core/walls.mjs instead. */\n';

mkdirSync(join(SITE, 'js'), { recursive: true });
mkdirSync(join(SITE, 'data'), { recursive: true });
mkdirSync(join(SITE, 'assets'), { recursive: true });

writeFileSync(join(SITE, 'js', 'walls.js'), BANNER + readFileSync(join(ROOT, 'src', 'core', 'walls.mjs'), 'utf8'));

const seed = JSON.parse(readFileSync(join(ROOT, 'data', 'seed.json'), 'utf8'));
writeFileSync(join(SITE, 'data', 'seed.json'), JSON.stringify(seed));

const assets = ['avatar.png', 'avatar-background.png', 'banner.png', 'social-card.png', 'how-it-works.svg'];
for (const a of assets) copyFileSync(join(ROOT, 'assets', a), join(SITE, 'assets', a));

process.stdout.write(`site synced · walls.js · seed.json (${seed.wallets.length} wallets, ${seed.tokens.length} tokens) · ${assets.length} assets\n`);
